# Generated by Django 3.0.4 on 2022-09-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rut',
        ),
    ]
